# ACOLITE external credential configuration

# It is recommented to use .netrc for configuration of your credentials
# As an alternative they can be configured here

[EarthData]  # EarthData credentials
# alternatively use .netrc for machine earthdata
u = ""
p = ""

[EarthExplorer]  # EarthExplorer credentials
# alternatively use .netrc for machine earthexplorer
u = ""
p = ""

[CDSE]  # CDSE credentials
# alternatively use .netrc for machine cdse
u = ""
p = ""
